### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [voidzero/omz-plugin-psgrep#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by voidzero** [comment]
Hey! That's pretty cool. I missed your comment entirely, sorry about that.

I've added the MIT license and a README.md. Please let me know when you've added it, thanks!

**Comment by unixorn** [comment]
It'll get added in today's changes.

**Comment by voidzero** [comment]
Very cool. First time my code got added like this. Thanks! Much appreciated. 👍
